import { useEffect, useState } from 'react';
import { CheckCircle2, CircleDot, Plus, Trash2 } from 'lucide-react';
import Seo from '../../components/ui/Seo.jsx';
import SectionCard from '../../components/portal/SectionCard.jsx';
import TextField from '../../components/ui/TextField.jsx';
import { createGoal, deleteGoal, listMyGoals, updateGoal } from '../../lib/supabase/platform.js';

export default function Goals() {
  const [goals, setGoals] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', description: '', target_date: '' });
  async function load() { try { setLoading(true); setGoals(await listMyGoals()); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function add(e) { e.preventDefault(); if (!form.title.trim()) return; try { await createGoal(form); setForm({ title:'', description:'', target_date:'' }); load(); } catch(e) { setError(e.message); } }
  return <><Seo title="Learning Goals" description="Plan and track your learning goals." path="/learn/goals"/><div><p className="eyebrow">Learning plan</p><h1 className="page-title">My Learning Goals</h1><p className="page-copy">Turn your programme and career goals into clear milestones.</p></div>{error&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><SectionCard title="Active goals">{loading?<p className="text-sm text-navy-500">Loading…</p>:!goals.length?<p className="text-sm text-navy-500">No goals yet. Add one to start planning.</p>:<div className="space-y-3">{goals.map(g=><div key={g.id} className="flex items-start justify-between gap-4 rounded-xl border border-navy-100 p-4"><div className="flex gap-3"><span className="mt-0.5 text-gold-600">{g.status==='completed'?<CheckCircle2 size={18}/>:<CircleDot size={18}/>}</span><div><h3 className="font-display font-bold text-navy-900">{g.title}</h3>{g.description&&<p className="mt-1 text-sm leading-6 text-navy-500">{g.description}</p>}{g.target_date&&<p className="mt-2 text-xs font-semibold text-navy-500">Target: {new Date(g.target_date).toLocaleDateString()}</p>}</div></div><div className="flex gap-1"><button className="rounded-lg px-2 py-1 text-xs font-semibold text-gold-700 hover:bg-gold-50" onClick={async()=>{await updateGoal(g.id,{status:g.status==='completed'?'active':'completed'});load();}}>{g.status==='completed'?'Reopen':'Complete'}</button><button aria-label="Delete goal" className="rounded-lg p-2 text-navy-400 hover:bg-red-50 hover:text-red-600" onClick={async()=>{await deleteGoal(g.id);load();}}><Trash2 size={15}/></button></div></div>)}</div>}</SectionCard><SectionCard title="Add a goal" description="Keep it specific and measurable."><form onSubmit={add} className="space-y-4"><TextField label="Goal" name="goal" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Complete Electrical Machines" required/><TextField label="Description" name="goal-description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What will success look like?" optional/><TextField label="Target date" name="target-date" type="date" value={form.target_date} onChange={e=>setForm({...form,target_date:e.target.value})} optional/><button className="btn-gold inline-flex items-center gap-2"><Plus size={15}/> Add goal</button></form></SectionCard></div></>;
}
