import { useEffect, useState } from 'react';
import { FolderKanban, Wrench, CheckCircle2 } from 'lucide-react';
import Seo from '../../components/ui/Seo.jsx';
import SectionCard from '../../components/portal/SectionCard.jsx';
import { joinProject, listProjects, submitProjectMilestone } from '../../lib/supabase/platform.js';

export default function Projects() {
  const [projects,setProjects]=useState([]); const [busy,setBusy]=useState(''); const [error,setError]=useState('');
  async function load(){try{setProjects(await listProjects());setError('')}catch(e){setError(e.message)}} useEffect(()=>{load()},[]);
  async function join(id){try{setBusy(id);await joinProject(id);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function submit(id){const comment=window.prompt('Describe what you completed for this milestone:');if(comment===null)return;try{setBusy(id);await submitProjectMilestone(id,{comment,status:'submitted'});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  return <><Seo title="Projects & Practical Labs" description="Build practical evidence through projects." path="/learn/projects"/><div><p className="eyebrow">Practical learning</p><h1 className="page-title">Projects & Practical Labs</h1><p className="page-copy">Build real evidence of your skills through guided projects and milestones.</p></div>{error&&<div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-6 grid gap-5 md:grid-cols-2">{projects.length===0?<SectionCard title="No published projects"><p className="text-sm text-navy-500">Projects published by instructors will appear here.</p></SectionCard>:projects.map(p=><SectionCard key={p.id} className="p-6"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-500/10 text-gold-700"><FolderKanban size={19}/></div><span className="rounded-full bg-navy-50 px-2.5 py-1 text-[11px] font-bold capitalize text-navy-600">{p.difficulty}</span></div><h2 className="mt-5 font-display text-xl font-bold text-navy-900">{p.title}</h2><p className="mt-2 text-sm leading-6 text-navy-500">{p.description||'A guided practical project.'}</p>{p.duration_weeks&&<p className="mt-3 text-xs font-semibold text-navy-500">{p.duration_weeks} weeks</p>}<button disabled={busy===p.id} onClick={()=>join(p.id)} className="btn-gold mt-5 text-sm">{busy===p.id?'Working…':'Join project'}</button>{p.project_milestones?.length>0&&<div className="mt-6 border-t border-navy-100 pt-5"><p className="text-xs font-bold uppercase tracking-wide text-navy-500">Milestones</p><div className="mt-3 space-y-2">{[...p.project_milestones].sort((a,b)=>a.position-b.position).map(m=><div key={m.id} className="flex items-center justify-between rounded-lg bg-navy-50/70 px-3 py-2"><span className="flex items-center gap-2 text-sm font-semibold text-navy-800"><Wrench size={14}/>{m.title}</span><button onClick={()=>submit(m.id)} className="text-xs font-bold text-gold-700">Submit</button></div>)}</div></div>}</SectionCard>)}</div></>;
}
