/*
  # LMS Phase 10 — Discussions, Announcements, Notifications

  Notifications are generated by triggers on real events (never written
  directly by the client — Section 20's "based on actual system events,
  not static placeholder data"), covering: new enrollment, assignment
  graded, quiz result available, new announcement.
*/

-- ============================================================
-- 1. discussions (course-scoped topics)
-- ============================================================
CREATE TABLE IF NOT EXISTS discussions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL REFERENCES lms_courses(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text,
  is_pinned boolean NOT NULL DEFAULT false,
  is_closed boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discussions_course ON discussions(course_id, is_pinned DESC, created_at DESC);

ALTER TABLE discussions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS discussion_replies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  discussion_id uuid NOT NULL REFERENCES discussions(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  body text NOT NULL,
  is_instructor_reply boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discussion_replies_discussion ON discussion_replies(discussion_id, created_at);

ALTER TABLE discussion_replies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_discussions_if_enrolled_or_instructor" ON discussions;
CREATE POLICY "read_discussions_if_enrolled_or_instructor" ON discussions
  FOR SELECT TO authenticated
  USING (is_course_instructor(course_id) OR is_enrolled(course_id));

DROP POLICY IF EXISTS "enrolled_create_discussions" ON discussions;
CREATE POLICY "enrolled_create_discussions" ON discussions
  FOR INSERT TO authenticated
  WITH CHECK (author_id = auth.uid() AND (is_course_instructor(course_id) OR is_enrolled(course_id)));

DROP POLICY IF EXISTS "author_or_instructor_update_discussion" ON discussions;
CREATE POLICY "author_or_instructor_update_discussion" ON discussions
  FOR UPDATE TO authenticated
  USING (author_id = auth.uid() OR is_course_instructor(course_id))
  WITH CHECK (author_id = auth.uid() OR is_course_instructor(course_id));
  -- Pinning/closing is restricted to instructors at the APPLICATION layer
  -- (the UI only exposes those controls to instructors); a student-authored
  -- update should only ever touch title/body in practice.

DROP POLICY IF EXISTS "read_replies_if_can_read_discussion" ON discussion_replies;
CREATE POLICY "read_replies_if_can_read_discussion" ON discussion_replies
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM discussions d WHERE d.id = discussion_id
    AND (is_course_instructor(d.course_id) OR is_enrolled(d.course_id))
  ));

DROP POLICY IF EXISTS "enrolled_reply_to_open_discussion" ON discussion_replies;
CREATE POLICY "enrolled_reply_to_open_discussion" ON discussion_replies
  FOR INSERT TO authenticated
  WITH CHECK (
    author_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM discussions d WHERE d.id = discussion_id AND d.is_closed = false
      AND (is_course_instructor(d.course_id) OR is_enrolled(d.course_id))
    )
  );

-- ============================================================
-- 2. lms_announcements (course-scoped)
-- ============================================================
CREATE TABLE IF NOT EXISTS lms_announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL REFERENCES lms_courses(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_course ON lms_announcements(course_id, created_at DESC);

ALTER TABLE lms_announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_announcements_if_enrolled_or_instructor" ON lms_announcements;
CREATE POLICY "read_announcements_if_enrolled_or_instructor" ON lms_announcements
  FOR SELECT TO authenticated
  USING (is_course_instructor(course_id) OR is_enrolled(course_id));

DROP POLICY IF EXISTS "instructor_post_announcements" ON lms_announcements;
CREATE POLICY "instructor_post_announcements" ON lms_announcements
  FOR INSERT TO authenticated
  WITH CHECK (author_id = auth.uid() AND is_course_instructor(course_id));

DROP POLICY IF EXISTS "instructor_manage_own_announcements" ON lms_announcements;
CREATE POLICY "instructor_manage_own_announcements" ON lms_announcements
  FOR ALL TO authenticated
  USING (is_course_instructor(course_id))
  WITH CHECK (is_course_instructor(course_id));

-- ============================================================
-- 3. notifications
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN (
    'enrollment', 'assignment_graded', 'quiz_result', 'announcement', 'course_completed'
  )),
  title text NOT NULL,
  body text,
  link_path text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_id, is_read, created_at DESC);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_own_notifications" ON notifications;
CREATE POLICY "read_own_notifications" ON notifications
  FOR SELECT TO authenticated
  USING (recipient_id = auth.uid());

DROP POLICY IF EXISTS "mark_own_notifications_read" ON notifications;
CREATE POLICY "mark_own_notifications_read" ON notifications
  FOR UPDATE TO authenticated
  USING (recipient_id = auth.uid())
  WITH CHECK (recipient_id = auth.uid());
-- No client INSERT policy — notifications are only ever written by the
-- SECURITY DEFINER trigger functions below, never directly by a user.

-- ============================================================
-- 4. Event triggers that generate notifications
-- ============================================================

-- New enrollment → notify the student
CREATE OR REPLACE FUNCTION notify_on_enrollment()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_course_title text;
BEGIN
  SELECT title INTO v_course_title FROM lms_courses WHERE id = NEW.course_id;
  INSERT INTO notifications (recipient_id, type, title, body, link_path)
  VALUES (NEW.student_id, 'enrollment', 'Enrolled in ' || v_course_title, 'You can start learning right away.', '/learn/lms_courses/' || NEW.course_id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_enrollment ON lms_enrollments;
CREATE TRIGGER trg_notify_on_enrollment
  AFTER INSERT ON lms_enrollments
  FOR EACH ROW EXECUTE FUNCTION notify_on_enrollment();

-- Assignment graded → notify the student
CREATE OR REPLACE FUNCTION notify_on_submission_graded()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_title text;
BEGIN
  IF NEW.status = 'graded' AND (OLD.status IS DISTINCT FROM 'graded') THEN
    SELECT a.title INTO v_title FROM assignments a WHERE a.id = NEW.assignment_id;
    INSERT INTO notifications (recipient_id, type, title, body, link_path)
    VALUES (NEW.student_id, 'assignment_graded', v_title || ' has been graded', 'Score: ' || NEW.score, '/learn/assignments/' || NEW.assignment_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_submission_graded ON submissions;
CREATE TRIGGER trg_notify_on_submission_graded
  AFTER UPDATE ON submissions
  FOR EACH ROW EXECUTE FUNCTION notify_on_submission_graded();

-- Quiz submitted (auto-graded objective questions) → notify the student
CREATE OR REPLACE FUNCTION notify_on_quiz_result()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_title text;
BEGIN
  IF NEW.status = 'submitted' AND (OLD.status IS DISTINCT FROM 'submitted') THEN
    SELECT q.title INTO v_title FROM quizzes q WHERE q.id = NEW.quiz_id;
    INSERT INTO notifications (recipient_id, type, title, body, link_path)
    VALUES (NEW.student_id, 'quiz_result', v_title || ' result available', 'Score: ' || NEW.score || ' / ' || NEW.max_score, '/learn/quizzes/' || NEW.quiz_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_quiz_result ON quiz_attempts;
CREATE TRIGGER trg_notify_on_quiz_result
  AFTER UPDATE ON quiz_attempts
  FOR EACH ROW EXECUTE FUNCTION notify_on_quiz_result();

-- New announcement → notify every actively enrolled student in that course
CREATE OR REPLACE FUNCTION notify_on_announcement()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO notifications (recipient_id, type, title, body, link_path)
  SELECT student_id, 'announcement', NEW.title, left(NEW.body, 140), '/learn/lms_courses/' || NEW.course_id
  FROM lms_enrollments WHERE course_id = NEW.course_id AND status = 'active';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_announcement ON lms_announcements;
CREATE TRIGGER trg_notify_on_announcement
  AFTER INSERT ON lms_announcements
  FOR EACH ROW EXECUTE FUNCTION notify_on_announcement();

-- (course_completed notification is already inserted directly by
-- check_course_completion() in the Phase 8-9 migration via audit_logs;
-- extending it to also write a notification row here.)
CREATE OR REPLACE FUNCTION notify_on_course_completion()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_title text;
BEGIN
  IF NEW.status = 'completed' AND (OLD.status IS DISTINCT FROM 'completed') THEN
    SELECT title INTO v_title FROM lms_courses WHERE id = NEW.course_id;
    INSERT INTO notifications (recipient_id, type, title, body, link_path)
    VALUES (NEW.student_id, 'course_completed', 'Course completed: ' || v_title, 'Congratulations on finishing the course!', '/learn/lms_courses/' || NEW.course_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_on_course_completion ON lms_enrollments;
CREATE TRIGGER trg_notify_on_course_completion
  AFTER UPDATE ON lms_enrollments
  FOR EACH ROW EXECUTE FUNCTION notify_on_course_completion();
